* Cronograma
** Febrero 08
- /Timothy Williamson/: Is Knowledge a State of Mind? 
** Febrero 15
-  /Elizabeth Fricker/: Is Knowing a State of Mind? The Case Against. En /Williamson on Knowledge/
** Febrero 22
- /Timothy Williamson/: 20. Knowledge First Epistemology. En /The Routledge Companion to Epistemology/
  - Trata temas como razones para actuar y la percepción (con la que queremos hacer una analogía respecto a las emociones.)
** Marzo 1
- /Laura Candiotto/: 1. From Philosophy of Emotion to Epistemology: Some Questions About the Epistemic Relevance of Emotions . En /The Value of emotions for Knowledge/.
* Otros textos
- Williamson on Knowledge
  - [Toda la parte de las respuestas]
- The Value of Emotions for Knowledge
  - 2. How Emotions Know: Naturalizing Epistemology via Emotions
    - Se centra en cómo se da la intencionalidad de las emociones /dada una perspectiva naturalista,/ por lo que no sé qué tan útil nos resulte :(
  - 4. A Pragmatist View of Emotions: Tracing Its Significance for the Current Debate
    - No me parece tan interesante ya que habla sólo de James y de Dewey.
